# The URL the site will be built for
base_url = "https://rust-community.pl"

title = "Homepage of the Polish Rust community"
description = "This site serves as an index for information about the Rust language community based in Poland."
author = "Jakub Beránek"
default_language = "en"

compile_sass = true
minify_html = true
build_search_index = false

generate_feeds = true
feed_limit = 50

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
github_url = "https://github.com/rust-community-pl/rust-community.pl"
